### ISSUE TITLE
Settings Inquiry

### ISSUE THREAD

**Issue by Lamiiine** [ahmetb/twitter-audit-log#3]
I am new to scraping and I am just wondering how is your code still scraping actual data from your Twitter account and the settings aren't set?
By settings I mean these keys and tokens

    TWITTER_BEARER_TOKEN
    TWITTER_CONSUMER_KEY
    TWITTER_CONSUMER_SECRET
    TWITTER_TOKEN_SECRET

**Comment by mattwelke** [comment]
The data comes from GitHub repo secrets:

```
${{ secrets.TWITTER_CONSUMER_KEY }}
```

It's injected into the environment variables of the GitHub Actions workflow as it runs. It's a way to have the GHA workflow file be public (in a public repo) without the secret being public. The secret is masked in the logs too if it's output into the logs of the GHA workflow.
